### ISSUE TITLE
date_default_timezone_set(): Timezone ID '' is invalid

### ISSUE THREAD

**Issue by BlazeNikhilesh** [modestkdr/Scrumwala#13]
I get this error after setting up the project.

Notice: date_default_timezone_set(): Timezone ID '' is invalid in /Applications/XAMPP/xamppfiles/htdocs/scrumwala/bootstrap/cache/compiled.php on line 1908

**Comment by chrisforrence** [comment]
Do you have an .env file at the project root? (If not, copy the .env.example file to .env)
