### ISSUE TITLE
ErrorException in McryptEncrypter.php

### ISSUE THREAD

**Issue by itahmid** [modestkdr/Scrumwala#24]
Am not sure if its a fault with my conf, 
ErrorException in McryptEncrypter.php line 93:
mcrypt_encrypt(): Key of size 12 not supported by this algorithm. Only keys of sizes 16, 24 or 32 supported

Also:
Does it create default DB entries or its supposed to be blank?
/var/www/html/learn_lara_apps/scrumwala$ php artisan migrate
Migration table created successfully.
Migrated: 2014_10_12_000000_create_users_table
Migrated: 2014_10_12_100000_create_password_resets_table
Migrated: 2015_03_21_193347_created_projects_table
Migrated: 2015_03_23_002913_create_sprint_statuses_table
Migrated: 2015_03_23_002915_create_issue_types_table
Migrated: 2015_03_23_002916_create_sprints_table
Migrated: 2015_03_23_002917_create_issue_statuses_table
Migrated: 2015_03_23_002918_create_issues_table
Migrated: 2015_06_20_144945_add_sort_order_columns_issues_table
Migrated: 2016_10_17_091929_add_default_value_to_issues_description_field

**Comment by itahmid** [comment]
![screenshot from 2016-12-23 15 25 04](https://cloud.githubusercontent.com/assets/1932385/21451374/b6aa082a-c924-11e6-8162-93e5e8bd3804.png)

**Comment by c10ce** [comment]
It looks like your .env file is missing a key.

    php artisan key:generate
