### ISSUE TITLE
Remove Project

### ISSUE THREAD

**Issue by hiddenicon** [modestkdr/Scrumwala#25]
Is there anyway to remove or archive projects? Either before their deadline or after?

**Comment by c10ce** [comment]
It doesn't look like there is a way within the application to remove projects. You'd need to use `php artisan tinker` to do that. @modestkdr would probably welcome a PR to do that within the application!

**Comment by hiddenicon** [comment]
I didn't see one either. I may work on that function and do a PR. Thanks!

**Comment by Srikanth-AD** [comment]
@hiddenicon  should be easy to add if you are interested in submitting a PR.
Example: Closing a sprint:
https://github.com/modestkdr/Scrumwala/blob/master/app/Http/Controllers/SprintsController.php#L98
